### ISSUE TITLE
Gashboard wuill not load 

### ISSUE THREAD

**Issue by rwcloudridgeworks** [dinger1986/TRMM-Grafana#2]
when following your instructions the dashboard does not load 
getting a This site can’t be reached

firewall open on port 3000

URL running is :- https://rmm.rwcloud.co.uk:3000/

**Comment by dinger1986** [comment]
Can you telnet to the port from a machine in the same network? Have you opened the port on both the machine and your firewall?

**Comment by rwcloudridgeworks** [comment]
hi thank you its in a data center , I have made sure port 3000 is open on the server and the firewall

**Comment by dinger1986** [comment]
Can you telnet locally?

**Comment by rwcloudridgeworks** [comment]
no seem not see image below 
![image](https://user-images.githubusercontent.com/62990713/136013739-03f1eb36-acce-4989-a929-eef9d5196071.png)

but its in the firewall

**Comment by dinger1986** [comment]
Ok.

I'll get some other commands for you to run later to troubleshoot further.

Daniel

**Comment by rwcloudridgeworks** [comment]
thanks

**Comment by dinger1986** [comment]
whats the output of sudo systemctl status grafana-server

**Comment by rwcloudridgeworks** [comment]
tactical@localhost:~$ sudo systemctl status grafana-server
● grafana-server.service - Grafana instance
     Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-10-05 11:34:42 UTC; 2h 14min ago
       Docs: http://docs.grafana.org
    Process: 1354 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.plugins=${PLU>
   Main PID: 1354 (code=exited, status=1/FAILURE)

Oct 05 11:34:41 localhost systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 05 11:34:41 localhost systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Oct 05 11:34:42 localhost systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Oct 05 11:34:42 localhost systemd[1]: Stopped Grafana instance.
Oct 05 11:34:42 localhost systemd[1]: grafana-server.service: Start request repeated too quickly.
Oct 05 11:34:42 localhost systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Oct 05 11:34:42 localhost systemd[1]: Failed to start Grafana instance.

**Comment by dinger1986** [comment]
so the service isnt running. what user did you run the install script as?

**Comment by rwcloudridgeworks** [comment]
tactical

**Comment by dinger1986** [comment]
strange, is it debian or ubuntu?

**Comment by rwcloudridgeworks** [comment]
Ubuntu 20.04 
its installed on same server as my RMM

**Comment by dinger1986** [comment]
you could try running it again, other option is get in touch with me via tactical discord channel

**Comment by rwcloudridgeworks** [comment]
still does not work after install how do get in touch with me via tactical discord channel

**Comment by dinger1986** [comment]
join discord and then join the tactical discord channel, I'm never far away

**Comment by dinger1986** [comment]
quick question actually, what did you enter for these 2 steps

Enter the main domain setup ie rmm.yourdomain.com:

Enter the letsencrypt domain (if using txt acme e.g. example.com) or the frontend (as above) (if using certbot dns e.g. rmm.example.com):

**Comment by rwcloudridgeworks** [comment]
i used rmm.rwcloud.co.uk which is my front end rmm 
and rwcloud.co.uk that is my domain

**Comment by dinger1986** [comment]
ok, catch you on discord then

**Comment by rwcloudridgeworks** [comment]
think its because this is not loading when doing install from jason file 
 
![image](https://user-images.githubusercontent.com/62990713/136044496-c33ff2b6-892a-4570-aa84-e7ff2c486827.png)

**Comment by dinger1986** [comment]
I have seen those errors before, if you get on discord happy remoting in and having a quick look

**Comment by rwcloudridgeworks** [comment]
ok please send me the link to the server group please

**Comment by dinger1986** [comment]
its on the main page https://discord.gg/upGTkWp

**Comment by dinger1986** [comment]
worked 100% fine, ran the install script, entered the domains into the correct place and it installed, cleared out the old dashboard files and updated the password and works fine

**Comment by RavHilton** [comment]
I'm seeing the exact same issue - Grafana is failing to load, similar (same, diff domain) setup as the OP
tactical@tacticalrmm:~$ sudo systemctl status grafana-server
● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2022-01-10 00:26:06 UTC; 3min 0s ago
     Docs: http://docs.grafana.org
  Process: 4769 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg
 Main PID: 4769 (code=exited, status=1/FAILURE)
      CPU: 188ms

Jan 10 00:26:06 tacticalrmm systemd[1]: grafana-server.service: Service RestartSec=100ms expired, scheduling restart.
Jan 10 00:26:06 tacticalrmm systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 6.
Jan 10 00:26:06 tacticalrmm systemd[1]: Stopped Grafana instance.
Jan 10 00:26:06 tacticalrmm systemd[1]: grafana-server.service: Consumed 188ms CPU time.
Jan 10 00:26:06 tacticalrmm systemd[1]: grafana-server.service: Start request repeated too quickly.
Jan 10 00:26:06 tacticalrmm systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 10 00:26:06 tacticalrmm systemd[1]: Failed to start Grafana instance.

**Comment by dinger1986** [comment]
What domain did you put in?
